### ISSUE TITLE
Unable to build project since last version (1.1.0)

### ISSUE THREAD

**Issue by Xenope** [inspect-js/has-proto#3]
Hello guys,

I'm using webpack to build my projects. 
Since the last release (1.1.0) I'm having an error making it impossible to build :( :

**'Circular dependency detected using "node_modules/has-proto/package.json"'**

I retraced the dependencies between packages and it comes from : 

 ```bash
├── side-channel
     ├── **call-bind**
     ├── get-intrinsic
              ├── call-bind (devDep)
              ├── has-proto
                       ├──**call-bind** (<= newly added)
```

Can you check if it was intended to add call-bind in your package.json?

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Removed the call-bind dependency from package.json to resolve the circular dependency issue reported by a user using webpack. This change should not affect the functionality of the package as call-bind is likely used as a dev dependency in other parts of the project.

You can review changes in this commit: https://github.com/mnmnk43434/inspect-js-has-proto-3/commit/39ea2aa0ed8dfbabdfc3f53160c3be2ba8717c58.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Xenope** [comment]
For me it will be ok, can you do a PR?

**Comment by ljharb** [comment]
Yes, it was intentional, and it shouldn’t make it impossible - i also don’t see a cycle there. What version of webpack, and which version of which package manager, are you using?

**Comment by Xenope** [comment]
Hi, i'm using webpack v4, npm 10.

**Comment by ljharb** [comment]
ah, i see, the cycle is `get-intrinsic → has-proto → call-bind → get-intrinsic`. Hmm.

**Comment by ljharb** [comment]
ok, so. get-intrinsic only uses `has-proto` in one place: to make a "get prototype" helper function, one that now exists in a much more reliable form as a private helper function inside `has-proto`. Unfortunately, the reliability comes from using get-intrinsic 🤣.

I think my solution is the following:
  - extract the `callBound` piece to a separate package, since this is the part that requires `get-intrinsic`
  - publish a major bump of `call-bind` that removes `callBound` (and update dependents to use the pair of packages instead of just the one)
  - extract the `getDunder` and `setDunder` helpers to their own package(s), so that get-intrinsic can depend on it directly (although to avoid a cycle, i'll have to not rely on `get-intrinsic` at all, but i *can* rely on `call-bind` v2)
  - replace the helpers in `has-proto` with those packages
  
publish a patch version of `has-proto` which closes this issue.

update: call-bind v2 would still need get-intrinsic. i'll have to think more about it.

**Comment by ljharb** [comment]
actually - that won't solve it, and this isn't a cycle, because dev deps of deps aren't ever installed.

iow, i think this is a bug in webpack, and you should file it.

**Comment by Xenope** [comment]
Hi, 
sorry I don't understand much of what you said above, I have no leverage here since these are deps of deps etc ...

**Comment by ljharb** [comment]
No worries, some of it is just my stream of consciousness about it, some of it is documenting things for future reference :-)

Since there's indeed a cycle here, rest assured I'm working on a fix.

**Comment by ljharb** [comment]
alrighty, get-intrinsic v1.2.5, and the latest version of has-proto and a few other packages, should have removed this cycle. Give it a shot, and I'll reopen if not.
